{% set name = "mo-imports" %}
{% set version = "7.584.24095" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mo-imports-{{ version }}.tar.gz
  sha256: 84c5c146a408aae8ac3976868cdb84d2906c1b671d2297c2c32dd3b0d28f2fdb

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - mo-future ==7.584.24095
    - python >={{ python_min }}

test:
  imports:
    - mo_imports
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/klahnakoski/mo-imports
  summary: More Imports! - Delayed importing
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
