{% set name = "mo-imports" %}
{% set version = "7.677.25059" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1d5bfb0db49d3be10f6be659139c9f724c15ca2bdbbc8091cb4980c499f50d6d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - mo-future ==7.676.25059
    - python >={{ python_min }}

test:
  imports:
    - mo_imports
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/klahnakoski/mo-imports
  summary: More Imports! - Delayed importing
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
